# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("scholar", "Candidate / Scholar"),
                            ("supervisor", "Supervisor"),
                            ("co_supervisor", "Co-Supervisor"),
                            ("tac_member", "TAC Member"),
                            ("sdrc", "SDRC"),
                            ("dc", "Doctoral Committee"),
                            ("dean_rd", "Dean / Dy. Dean R&D"),
                            ("vc", "Vice-Chancellor"),
                            ("coe", "Controller of Examinations"),
                            ("registrar", "Registrar"),
                            ("hr", "HR Office"),
                            ("rd_office", "R&D Office"),
                            ("course_coordinator", "Course Coordinator"),
                            ("external_examiner", "External Examiner"),
                            ("dpep_member", "DPEP Member"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "own_scholar_only",
                    models.BooleanField(
                        default=False,
                        help_text="Approver must be this scholar's own supervisor/co-supervisor/TAC member",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["chain", "order"],
            },
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DC", "Doctoral Committee"),
                            ("SDRC", "School Doctoral Research Committee"),
                            ("DPEP", "Dissertation Presentation Evaluation Panel"),
                            ("EXAM", "Examination Committee"),
                            ("PROPOSAL", "Research Proposal Evaluation Committee"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tenure_start", models.DateField(blank=True, null=True)),
                ("tenure_end", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommitteeMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CHAIR", "Chair"),
                            ("CONVENER", "Convener"),
                            ("MEMBER", "Member"),
                            ("EXTERNAL", "External Expert"),
                        ],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("ASSISTANT_PROFESSOR", "Assistant Professor"),
                            ("ASSOCIATE_PROFESSOR", "Associate Professor"),
                            ("PROFESSOR", "Professor"),
                            ("OTHER", "Other / External"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True, help_text="For external faculty", max_length=255
                    ),
                ),
                ("is_external", models.BooleanField(default=False)),
                ("superannuation_date", models.DateField(blank=True, null=True)),
                (
                    "capacity_override",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Only with a recorded DC/VC approval",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faculty",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=60)),
                (
                    "scholar_category",
                    models.CharField(
                        blank=True, help_text="Blank = all categories", max_length=30
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "scholar_category"),
                        name="uniq_chain_code_category",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved", models.BooleanField()),
                ("remarks", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["decided_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.approvalchain",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
