# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("scholars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="scholar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="approvaldecision",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="core.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="core.approvalchain",
            ),
        ),
        migrations.AddField(
            model_name="approvaldecision",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.approvalstep"
            ),
        ),
        migrations.AddField(
            model_name="committeemembership",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.committee",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="committeemembership",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.faculty"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="core.school",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalstep",
            constraint=models.UniqueConstraint(
                fields=("chain", "order"), name="uniq_step_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="committeemembership",
            constraint=models.UniqueConstraint(
                fields=("committee", "faculty"), name="uniq_committee_member"
            ),
        ),
    ]
