# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor"),
                            ("CO_SUPERVISOR", "Co-Supervisor"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Set when the assignment ends or is replaced",
                        null=True,
                    ),
                ),
                (
                    "approved_on",
                    models.DateField(
                        blank=True,
                        help_text="DC approval date; null while pending",
                        null=True,
                    ),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervisions",
                        to="core.faculty",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_assignments",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True), ("kind", "SUPERVISOR")
                        ),
                        fields=("scholar",),
                        name="one_open_supervisor_per_scholar",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("scholar", "faculty"),
                        name="no_duplicate_open_supervision",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TACMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SUPERVISOR", "Supervisor (ex officio)"),
                            ("MEMBER", "Interdisciplinary member"),
                        ],
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("approved_on", models.DateField(blank=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tac_memberships",
                        to="core.faculty",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tac_memberships",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("scholar", "faculty"),
                        name="no_duplicate_open_tac_seat",
                    )
                ],
            },
        ),
    ]
