# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2026-SEP", max_length=50, unique=True
                    ),
                ),
                ("vacancy_notified_on", models.DateField(blank=True, null=True)),
                ("rpet_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT_SPONSORED", "Part-time: Sponsored"),
                            ("PT_SISTER", "Part-time: Sister Institution"),
                            ("PT_EXTERNAL", "Part-time: External"),
                            ("PT_INTERNAL", "Part-time: Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_qualification",
                    models.CharField(
                        choices=[
                            ("BTECH", "B.Tech (23 credits)"),
                            ("MTECH", "M.Tech / M.E. / M.Pharm (17 credits)"),
                            (
                                "PG",
                                "Integrated / M.Sc / MCA / MBA / M.Com (20 credits)",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "statement_of_purpose",
                    models.FileField(blank=True, upload_to="applications/sop/"),
                ),
                ("cv", models.FileField(blank=True, upload_to="applications/cv/")),
                (
                    "exemption",
                    models.CharField(
                        blank=True,
                        help_text="GATE / NET / CSIR ... if exempt from RPET",
                        max_length=20,
                    ),
                ),
                (
                    "rpet_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interview_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="scholars.admissioncycle",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scholar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prn",
                    models.CharField(max_length=30, unique=True, verbose_name="PRN"),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "pwd_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="PwD %",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time"),
                            ("PT_SPONSORED", "Part-time: Sponsored"),
                            ("PT_SISTER", "Part-time: Sister Institution"),
                            ("PT_EXTERNAL", "Part-time: External"),
                            ("PT_INTERNAL", "Part-time: Internal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_qualification",
                    models.CharField(
                        choices=[
                            ("BTECH", "B.Tech (23 credits)"),
                            ("MTECH", "M.Tech / M.E. / M.Pharm (17 credits)"),
                            (
                                "PG",
                                "Integrated / M.Sc / MCA / MBA / M.Com (20 credits)",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("research_area", models.CharField(blank=True, max_length=255)),
                ("admission_date", models.DateField()),
                (
                    "registration_date",
                    models.DateField(
                        blank=True, help_text="Provisional registration", null=True
                    ),
                ),
                ("registration_fee_paid", models.BooleanField(default=False)),
                (
                    "sponsorship_letter",
                    models.FileField(
                        blank=True,
                        help_text="Required for part-time sponsored / sister-institution",
                        upload_to="scholars/sponsorship/",
                    ),
                ),
                (
                    "fellowship",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("JRF", "Junior Research Fellow"),
                            ("SRF", "Senior Research Fellow"),
                        ],
                        default="NONE",
                        max_length=4,
                    ),
                ),
                ("fellowship_start", models.DateField(blank=True, null=True)),
                (
                    "phase",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Admission"),
                            (2, "Coursework"),
                            (3, "Supervisor & TAC"),
                            (4, "Research Proposal"),
                            (5, "Progress Monitoring"),
                            (6, "Pre-submission Synopsis"),
                            (7, "Thesis Submission"),
                            (8, "Thesis Evaluation"),
                            (9, "Dissertation Presentation / Viva"),
                            (10, "Degree Award"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("AWARDED", "Degree awarded"),
                            ("CANCELLED", "Registration cancelled"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("ON_BREAK", "Career break / semester break"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("coursework_completed_on", models.DateField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scholars.application",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["prn"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual leave"),
                            ("MATERNITY", "Maternity leave"),
                            ("CAREER_BREAK", "Career break"),
                            ("SEMESTER_BREAK", "Semester break"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SYNOPSIS", "Synopsis +1 year"),
                            ("THESIS_SUBMISSION", "Thesis submission +3 months"),
                            ("RE_REGISTRATION", "Re-registration +2 years"),
                            ("RELAXATION", "Female / PwD relaxation +2 years"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("GRANTED", "Granted"),
                            ("REFUSED", "Refused"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("requested_on", models.DateField(auto_now_add=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extensions",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "GRANTED")),
                        fields=("scholar", "kind"),
                        name="uniq_granted_extension",
                    )
                ],
            },
        ),
    ]
