# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 2026-ODD", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("fee_deadline", models.DateField()),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="GrantClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                (
                    "amount_claimed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_approved",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("receipts", models.FileField(blank=True, upload_to="grants/")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("submitted_on", models.DateField(auto_now_add=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_claims",
                        to="scholars.scholar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TARegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_submitted_on", models.DateField()),
                ("fee_receipt", models.FileField(blank=True, upload_to="ta/receipts/")),
                ("expertise", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("LISTED", "Shared with Schools"),
                            ("INDUCTED", "Inducted"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="REGISTERED",
                        max_length=12,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ta_registrations",
                        to="scholars.scholar",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TAFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("FACULTY", "Faculty"),
                            ("DIRECTOR", "School Director"),
                            ("STUDENTS", "Students"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="1-5")),
                ("satisfactory", models.BooleanField()),
                ("comments", models.TextField(blank=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="finance.taregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TAAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("hours_per_week", models.PositiveSmallIntegerField()),
                ("contact_hours_per_week", models.PositiveSmallIntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.faculty"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.school"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="finance.taregistration",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="taregistration",
            constraint=models.UniqueConstraint(
                fields=("scholar", "semester"), name="uniq_ta_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="tafeedback",
            constraint=models.UniqueConstraint(
                fields=("registration", "source"), name="uniq_ta_feedback_source"
            ),
        ),
    ]
