# Generated by Django 5.2.17 on 2026-09-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0002_academicruleparameter_academicyear_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="academic_semester",
            field=models.OneToOneField(
                blank=True,
                help_text="Canonical academic semester this TA semester belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ta_semester",
                to="coursework.semester",
            ),
        ),
    ]
