# Generated by Django 5.2.17 on 2026-09-25 15:02

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("scholars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "faculty_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to="core.faculty",
                    ),
                ),
                (
                    "scholar_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to="scholars.scholar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Login account (IdP subject)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="CapabilityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("SCHOLAR", "Scholar"),
                            ("FACULTY", "Faculty"),
                            ("SUPERVISOR", "Supervisor"),
                            ("DEPARTMENT_ADMIN", "Department admin"),
                            ("SCHOOL_ADMIN", "School admin"),
                            ("SDRC_MEMBER", "SDRC member"),
                            ("DC_MEMBER", "DC member"),
                            ("EXAM_EVALUATOR", "Exam evaluator"),
                            ("PHD_CELL_OPERATOR", "PhD Cell operator"),
                            ("ACADEMIC_ADMIN", "Academic admin"),
                            ("DEAN_RND", "Dean R&D"),
                            ("COE_OPERATOR", "COE operator"),
                            ("VC_OPERATOR", "VC operator"),
                            ("SYSTEM_ADMIN", "System admin"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("INSTITUTION", "Institution"),
                            ("SCHOOL", "School"),
                            ("DEPARTMENT", "Department"),
                            ("COMMITTEE", "Committee"),
                            ("SCHOLAR", "Single scholar"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "basis",
                    models.CharField(
                        help_text="Why this was granted (order no., approval ref)",
                        max_length=255,
                    ),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.department",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="scholars.scholar",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.school",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null only for the system bootstrap",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_assignments",
                        to="identity.person",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "ordering": ["person", "capability"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capability_used", models.CharField(blank=True, max_length=30)),
                ("action", models.CharField(max_length=100)),
                ("resource_type", models.CharField(blank=True, max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("allowed", models.BooleanField()),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64, unique=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uniq_person_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("department__isnull", True),
                        ("scholar__isnull", True),
                        ("school__isnull", True),
                        ("scope_type", "INSTITUTION"),
                    ),
                    models.Q(
                        ("department__isnull", True),
                        ("scholar__isnull", True),
                        ("school__isnull", False),
                        ("scope_type", "SCHOOL"),
                    ),
                    models.Q(
                        ("department__isnull", False),
                        ("scholar__isnull", True),
                        ("school__isnull", True),
                        ("scope_type", "DEPARTMENT"),
                    ),
                    models.Q(
                        ("department__isnull", True),
                        ("scholar__isnull", False),
                        ("school__isnull", True),
                        ("scope_type", "SCHOLAR"),
                    ),
                    _connector="OR",
                ),
                name="capability_scope_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "capability__in",
                        ["SCHOLAR", "DC_MEMBER", "SDRC_MEMBER", "FACULTY"],
                    ),
                    _negated=True,
                ),
                name="capability_not_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="capability_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("scope_type", "INSTITUTION")
                ),
                fields=("person", "capability"),
                name="uniq_active_grant_institution",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("scope_type", "SCHOOL")
                ),
                fields=("person", "capability", "school"),
                name="uniq_active_grant_school",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("scope_type", "DEPARTMENT")
                ),
                fields=("person", "capability", "department"),
                name="uniq_active_grant_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("scope_type", "SCHOLAR")
                ),
                fields=("person", "capability", "scholar"),
                name="uniq_active_grant_scholar",
            ),
        ),
    ]
