# Generated by Django 5.2.17 on 2026-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("identity", "0001_initial"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="capabilityassignment",
            name="capability_not_derived",
        ),
        migrations.AlterField(
            model_name="capabilityassignment",
            name="capability",
            field=models.CharField(
                choices=[
                    ("SCHOLAR", "Scholar"),
                    ("FACULTY", "Faculty"),
                    ("SUPERVISOR", "Supervisor"),
                    ("DEPARTMENT_ADMIN", "Department admin"),
                    ("SCHOOL_ADMIN", "School admin"),
                    ("SDRC_MEMBER", "SDRC member"),
                    ("DC_MEMBER", "DC member"),
                    ("EXAM_EVALUATOR", "Exam evaluator"),
                    ("PHD_CELL_OPERATOR", "PhD Cell operator"),
                    ("RND_CELL_OPERATOR", "R&D Cell operator"),
                    ("CISR_OPERATOR", "CISR operator"),
                    ("ACADEMIC_ADMIN", "Academic admin"),
                    ("DEAN_RND", "Dean R&D"),
                    ("COE_OPERATOR", "COE operator"),
                    ("VC_OPERATOR", "VC operator"),
                    ("SYSTEM_ADMIN", "System admin"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "capability__in",
                        ["FACULTY", "SDRC_MEMBER", "DC_MEMBER", "SCHOLAR"],
                    ),
                    _negated=True,
                ),
                name="capability_not_derived",
            ),
        ),
    ]
