# Generated by Django 5.2.17 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_university_school_university"),
        ("identity", "0002_academic_capabilities"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="capabilityassignment",
            name="capability_not_derived",
        ),
        migrations.AddConstraint(
            model_name="capabilityassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "capability__in",
                        ["DC_MEMBER", "FACULTY", "SCHOLAR", "SDRC_MEMBER"],
                    ),
                    _negated=True,
                ),
                name="capability_not_derived",
            ),
        ),
    ]
