# Generated by Django 5.2.17 on 2026-09-26 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0003_stable_derived_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_type", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEWED", "Previewed (nothing written)"),
                            ("COMMITTED", "Committed"),
                        ],
                        default="PREVIEWED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=5)),
                ("file_size", models.PositiveIntegerField()),
                ("file_sha256", models.CharField(max_length=64)),
                ("sheet_name", models.CharField(blank=True, max_length=100)),
                (
                    "header_row",
                    models.PositiveIntegerField(
                        help_text="1-based row number of the header in the sheet"
                    ),
                ),
                (
                    "mapping",
                    models.JSONField(
                        help_text="Confirmed mapping: column index (string) → field name"
                    ),
                ),
                (
                    "mapping_sources",
                    models.JSONField(
                        default=dict,
                        help_text="How each column was mapped (exact/alias/ai/manual)",
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                ("rows_total", models.PositiveIntegerField()),
                (
                    "counts",
                    models.JSONField(
                        default=dict, help_text="Rows per status in the preview"
                    ),
                ),
                (
                    "report",
                    models.JSONField(
                        default=list, help_text="Per-row status, key and reasons"
                    ),
                ),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                (
                    "created_refs",
                    models.JSONField(
                        default=list,
                        help_text="Model label and id of each record created",
                    ),
                ),
                ("provisioned_person_ids", models.JSONField(default=list)),
                (
                    "audit_event_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Audit event recording the commit (correlation)",
                        null=True,
                    ),
                ),
                (
                    "committed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("committed_at__isnull", True), ("status", "PREVIEWED")
                            ),
                            models.Q(
                                ("committed_at__isnull", False),
                                ("committed_by__isnull", False),
                                ("status", "COMMITTED"),
                            ),
                            _connector="OR",
                        ),
                        name="import_commit_fields",
                    )
                ],
            },
        ),
    ]
