# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("credits", models.PositiveSmallIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory"),
                            ("ELECTIVE", "Elective"),
                            ("ACTIVITY", "Activity"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "required_for_all",
                    models.BooleanField(
                        default=True,
                        help_text="Part of the common core for every entry category",
                    ),
                ),
                (
                    "has_ethics_submodule",
                    models.BooleanField(
                        default=False,
                        help_text="Ethics sub-module must be cleared independently",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_gate", models.BooleanField(default=False)),
                (
                    "gate_min_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="coursework.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField()),
                ("exam_date", models.DateField()),
                (
                    "marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "special_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "-"),
                            ("I", "Incomplete"),
                            ("RW", "Re-register"),
                            ("AB", "Absent"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                ("ethics_cleared", models.BooleanField(blank=True, null=True)),
                ("grade", models.CharField(blank=True, max_length=2)),
                (
                    "grade_point",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursework.course",
                    ),
                ),
                (
                    "override",
                    models.ForeignKey(
                        blank=True,
                        help_text="VC override for a 3rd attempt / out-of-window attempt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_attempts",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["scholar", "course", "attempt_no"],
            },
        ),
        migrations.CreateModel(
            name="ComponentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coursework.assessmentcomponent",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_scores",
                        to="coursework.courseattempt",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="courseattempt",
            constraint=models.UniqueConstraint(
                fields=("scholar", "course", "attempt_no"), name="uniq_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentscore",
            constraint=models.UniqueConstraint(
                fields=("attempt", "component"), name="uniq_component_score"
            ),
        ),
    ]
