# Generated by Django 5.2.17 on 2026-09-25 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_activity_courses(apps, schema_editor):
    """Existing ACTIVITY courses must satisfy the new consistency constraint."""
    Course = apps.get_model("coursework", "Course")
    types = {"SIS7005": "INDUSTRIAL_TRAINING", "SIS7006": "CONFERENCE_WORKSHOP", "SIS7007": "RESEARCH_SEMINAR"}
    for course in Course.objects.filter(category="ACTIVITY"):
        course.evaluation_body = "SDRC"
        course.activity_type = course.activity_type or types.get(course.code, "RESEARCH_SEMINAR")
        course.save(update_fields=["evaluation_body", "activity_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_university_school_university"),
        ("coursework", "0001_initial"),
        ("identity", "0002_academic_capabilities"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicRuleParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed by the supplied source"),
                            (
                                "CONFIGURABLE",
                                "Configurable (value known, pending institutional confirmation)",
                            ),
                            (
                                "AMBIGUOUS",
                                "Ambiguous (sources conflict or wording unclear)",
                            ),
                            (
                                "UNRESOLVED",
                                "Unresolved (no value; requires institutional decision)",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Document / dataset the value comes from",
                        max_length=255,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Decision-sheet IDs, e.g. RD-01, RD-02",
                        max_length=100,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("change_reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["key", "version"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 2026-27", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivitySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artefact",
                    models.CharField(
                        choices=[
                            ("PLAN", "Training plan"),
                            ("LOGBOOK", "Logbook"),
                            ("REPORT", "Report"),
                            ("POSTER", "Poster"),
                            ("REFLECTIVE_NOTE", "Reflective note"),
                            ("PARTICIPATION_EVIDENCE", "Participation evidence"),
                            ("PRESENTATION", "Seminar presentation"),
                        ],
                        max_length=22,
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, upload_to="coursework/activities/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("ACCEPTED", "Accepted by SDRC"),
                            ("RETURNED", "Returned for revision"),
                        ],
                        default="SUBMITTED",
                        max_length=9,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_remarks", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["enrollment", "submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTINUOUS", "Continuous Assessment"),
                            ("END_TERM", "End-term evaluation"),
                            ("ACTIVITY", "Activity evaluation (SDRC)"),
                            (
                                "MANDATORY_MODULE",
                                "Mandatory module (cleared / not cleared)",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent of the course total; 0 for mandatory modules",
                        max_digits=5,
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Empty for mandatory modules (cleared / not cleared)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "reweighting_reference",
                    models.CharField(
                        blank=True,
                        help_text="Approval reference when an elective is re-weighted",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["offering", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=7)),
                ("old_mode", models.CharField(blank=True, max_length=8)),
                ("new_status", models.CharField(max_length=7)),
                ("new_mode", models.CharField(blank=True, max_length=8)),
                ("reason", models.CharField(max_length=255)),
                (
                    "corrected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PRESENT", "Present"), ("ABSENT", "Absent")],
                        max_length=7,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("PHYSICAL", "Physical"), ("ONLINE", "Online")],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("OPEN", "Open for enrollment"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PLANNED",
                        max_length=8,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["semester__start_date", "course__code"],
            },
        ),
        migrations.CreateModel(
            name="CourseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=3)),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("ABSENT", "Absent"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Why the outcome is what it is",
                    ),
                ),
                (
                    "rule_versions",
                    models.JSONField(
                        default=dict, help_text="{parameter key: version} used"
                    ),
                ),
                (
                    "is_provisional",
                    models.BooleanField(
                        help_text="Computed with AMBIGUOUS / UNRESOLVED parameters"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARED", "Prepared"),
                            ("VERIFIED", "Verified by R&D Cell"),
                            ("RATIFIED", "Ratified by COE"),
                            ("RETURNED", "Returned for correction"),
                        ],
                        default="PREPARED",
                        max_length=9,
                    ),
                ),
                ("prepared_as", models.CharField(max_length=30)),
                (
                    "prepared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("ratified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ElectiveProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_code",
                    models.CharField(
                        blank=True,
                        help_text="For a course not yet in the catalogue",
                        max_length=20,
                    ),
                ),
                ("proposed_title", models.CharField(blank=True, max_length=200)),
                ("credits", models.PositiveSmallIntegerField()),
                ("justification", models.TextField()),
                ("research_relevance", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("SUPERVISOR_RECOMMENDED", "Recommended by supervisor"),
                            (
                                "SUPERVISOR_NOT_RECOMMENDED",
                                "Not recommended by supervisor",
                            ),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        max_length=26,
                    ),
                ),
                ("supervisor_at", models.DateTimeField(blank=True, null=True)),
                ("supervisor_remarks", models.TextField(blank=True)),
                (
                    "decided_as",
                    models.CharField(
                        blank=True,
                        help_text="Capability used for the decision",
                        max_length=30,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_remarks", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectiveProposalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("capability", models.CharField(max_length=30)),
                ("remarks", models.TextField(blank=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_on", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["scheduled_on", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("registration_opens", models.DateField()),
                ("registration_closes", models.DateField()),
                ("exam_start", models.DateField()),
                ("exam_end", models.DateField()),
            ],
            options={
                "ordering": ["exam_start"],
            },
        ),
        migrations.CreateModel(
            name="ExamEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eligible", models.BooleanField()),
                ("attempt_no", models.PositiveSmallIntegerField(null=True)),
                ("reasons", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("rule_versions", models.JSONField(default=dict)),
                (
                    "evaluated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REGISTERED",
                        max_length=10,
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacultySubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INSTRUCTOR", "Instructor (section)"),
                            ("COURSE_COORDINATOR", "Course Coordinator (offering)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("basis", models.CharField(max_length=255)),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_absent", models.BooleanField(default=False)),
                (
                    "cleared",
                    models.BooleanField(
                        blank=True, help_text="Mandatory modules only", null=True
                    ),
                ),
                ("entered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarkEntryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_marks",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("old_is_absent", models.BooleanField()),
                ("old_cleared", models.BooleanField(null=True)),
                (
                    "new_marks",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("new_is_absent", models.BooleanField()),
                ("new_cleared", models.BooleanField(null=True)),
                ("reason", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="OrientationAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrientationSeminar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("held_on", models.DateField()),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ResultEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PREPARE", "Prepared"),
                            ("VERIFY", "Verified"),
                            ("RATIFY", "Ratified"),
                            ("RETURN", "Returned"),
                        ],
                        max_length=7,
                    ),
                ),
                ("capability", models.CharField(max_length=30)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScholarCourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENROLLED", "Enrolled"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("COMPLETED", "Completed (result ratified: pass)"),
                        ],
                        default="ENROLLED",
                        max_length=10,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["scholar", "offering"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["offering", "code"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("JAN_JUN", "January–June"),
                            ("JUL_DEC", "July–December"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Winter 2027'", max_length=60
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "elective_registration_deadline",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="ThirdAttemptCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts_used", models.PositiveSmallIntegerField()),
                (
                    "previous_attempts",
                    models.JSONField(
                        default=list, help_text="Snapshot of prior attempts and results"
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(blank=True, upload_to="coursework/third_attempt/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("DEAN_RECOMMENDED", "Recommended by Dean R&D"),
                            ("DEAN_NOT_RECOMMENDED", "Not recommended by Dean R&D"),
                            ("VC_APPROVED", "Approved by VC"),
                            ("VC_REJECTED", "Rejected by VC"),
                            ("CONSUMED", "Used for the third attempt"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dean_at", models.DateTimeField(blank=True, null=True)),
                ("dean_remarks", models.TextField(blank=True)),
                ("vc_at", models.DateTimeField(blank=True, null=True)),
                ("vc_remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThirdAttemptCaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=30)),
                ("capability", models.CharField(max_length=30)),
                ("remarks", models.TextField(blank=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-"),
                    ("INDUSTRIAL_TRAINING", "Industrial Training / Field Work"),
                    ("CONFERENCE_WORKSHOP", "Conference / Workshop participation"),
                    ("RESEARCH_SEMINAR", "Research Seminar Presentation"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="applicable_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Scholar coursework categories, e.g. ["I","II","III"]; empty = all',
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning department; empty = institution-level (e.g. CISR courses)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="evaluation_body",
            field=models.CharField(
                choices=[
                    ("COURSE_COORDINATOR", "Course Coordinator"),
                    ("SDRC", "SDRC (activity-based evaluation)"),
                ],
                default="COURSE_COORDINATOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="courseattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy record"),
                    ("SCHEDULED", "Scheduled / under evaluation"),
                    ("RESULT_RATIFIED", "Result ratified"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="LEGACY",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                choices=[
                    ("MANDATORY", "Mandatory taught course"),
                    ("ELECTIVE", "Elective"),
                    ("ACTIVITY", "Mandatory activity component"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                help_text="LEGACY: use FacultySubjectAssignment(role=COURSE_COORDINATOR)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="courseattempt",
            name="override",
            field=models.ForeignKey(
                blank=True,
                help_text="LEGACY: VC override for a 3rd attempt (see ThirdAttemptCase)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.approvalrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("credits__gt", 0)), name="course_credits_positive"
            ),
        ),
        migrations.RunPython(backfill_activity_courses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category", "ACTIVITY"),
                        ("evaluation_body", "SDRC"),
                        models.Q(("activity_type", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("category", "ACTIVITY"), _negated=True),
                        ("activity_type", ""),
                        ("evaluation_body", "COURSE_COORDINATOR"),
                    ),
                    _connector="OR",
                ),
                name="course_activity_consistency",
            ),
        ),
        migrations.AddField(
            model_name="academicruleparameter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Null only for the initial seed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="academic_year_dates",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="corrected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="coursework.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.faculty",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="coursework.attendancesession",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offerings",
                to="coursework.course",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="coursework.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="attempt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="result",
                to="coursework.courseattempt",
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="prepared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="ratified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="An elective already in the catalogue",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.course",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="elective_proposals",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="supervisor_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposalevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposalevent",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="coursework.electiveproposal",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="coursework.course",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="coursework.examcycle",
            ),
        ),
        migrations.AddField(
            model_name="exameligibility",
            name="evaluated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="exameligibility",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eligibility_checks",
                to="coursework.exam",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="attempt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration",
                to="coursework.courseattempt",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="eligibility",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration",
                to="coursework.exameligibility",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="coursework.exam",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="registered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="facultysubjectassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="facultysubjectassignment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_assignments",
                to="core.faculty",
            ),
        ),
        migrations.AddField(
            model_name="facultysubjectassignment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculty_assignments",
                to="coursework.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="facultysubjectassignment",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="markentry",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marks",
                to="coursework.assessment",
            ),
        ),
        migrations.AddField(
            model_name="markentry",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mark_entries",
                to="coursework.courseattempt",
            ),
        ),
        migrations.AddField(
            model_name="markentry",
            name="entered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="markentryhistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="markentryhistory",
            name="mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history",
                to="coursework.markentry",
            ),
        ),
        migrations.AddField(
            model_name="orientationattendance",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="orientationattendance",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="orientationseminar",
            name="organised_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.committee",
            ),
        ),
        migrations.AddField(
            model_name="orientationattendance",
            name="seminar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance",
                to="coursework.orientationseminar",
            ),
        ),
        migrations.AddField(
            model_name="resultevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="resultevent",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="coursework.courseresult",
            ),
        ),
        migrations.AddField(
            model_name="scholarcourseenrollment",
            name="elective_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="coursework.electiveproposal",
            ),
        ),
        migrations.AddField(
            model_name="scholarcourseenrollment",
            name="enrolled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="scholarcourseenrollment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="coursework.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="scholarcourseenrollment",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_enrollments",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam_registrations",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="exameligibility",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity_submissions",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="courseattempt",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_no__gte", 1), ("attempt_no__lte", 3)),
                name="attempt_no_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("marks__isnull", True),
                    models.Q(("marks__gte", 0), ("marks__lte", 100)),
                    _connector="OR",
                ),
                name="attempt_marks_range",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="coursework.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="scholarcourseenrollment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollments",
                to="coursework.section",
            ),
        ),
        migrations.AddField(
            model_name="facultysubjectassignment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="faculty_assignments",
                to="coursework.section",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_sessions",
                to="coursework.section",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semesters",
                to="coursework.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="orientationseminar",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orientation_seminars",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="examcycle",
            name="semester",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exam_cycle",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="electiveproposal",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offerings",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="dean_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="third_attempt_cases",
                to="coursework.scholarcourseenrollment",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.faculty",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="third_attempt_cases",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcase",
            name="vc_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="examregistration",
            name="third_attempt_case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registration",
                to="coursework.thirdattemptcase",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcaseevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="thirdattemptcaseevent",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="coursework.thirdattemptcase",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicruleparameter",
            constraint=models.UniqueConstraint(
                fields=("key", "version"), name="uniq_rule_param_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.UniqueConstraint(
                fields=("offering", "name"), name="uniq_assessment_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "MANDATORY_MODULE"),
                        ("max_marks__isnull", True),
                        ("weight", 0),
                    ),
                    models.Q(
                        models.Q(("kind", "MANDATORY_MODULE"), _negated=True),
                        ("max_marks__gt", 0),
                        ("weight__gt", 0),
                        ("weight__lte", 100),
                    ),
                    _connector="OR",
                ),
                name="assessment_weight_and_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_marks__isnull", True),
                    models.Q(("total_marks__gte", 0), ("total_marks__lte", 100)),
                    _connector="OR",
                ),
                name="result_total_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ratified_at__isnull", True),
                    ("verified_at__isnull", False),
                    _connector="OR",
                ),
                name="result_custody_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                fields=("cycle", "course"), name="uniq_exam_cycle_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="exam_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="markentry",
            constraint=models.UniqueConstraint(
                fields=("assessment", "attempt"), name="uniq_mark_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="markentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cleared__isnull", True),
                        ("is_absent", True),
                        ("marks__isnull", True),
                    ),
                    models.Q(
                        ("cleared__isnull", True),
                        ("is_absent", False),
                        ("marks__gte", 0),
                        ("marks__isnull", False),
                    ),
                    models.Q(
                        ("cleared__isnull", False),
                        ("is_absent", False),
                        ("marks__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="mark_entry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationattendance",
            constraint=models.UniqueConstraint(
                fields=("seminar", "scholar"), name="uniq_ros_attendance"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                fields=("session", "enrollment"), name="uniq_attendance_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "PRESENT"), models.Q(("mode", ""), _negated=True)
                    ),
                    models.Q(("mode", ""), ("status", "ABSENT")),
                    _connector="OR",
                ),
                name="attendance_mode_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitysubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "RETURNED"), _negated=True),
                fields=("enrollment", "artefact"),
                name="one_live_artefact_submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("offering", "code"), name="uniq_section_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarcourseenrollment",
            constraint=models.UniqueConstraint(
                fields=("scholar", "offering"), name="uniq_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultysubjectassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "INSTRUCTOR"), ("section__isnull", False)),
                    models.Q(("role", "COURSE_COORDINATOR"), ("section__isnull", True)),
                    _connector="OR",
                ),
                name="assignment_role_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultysubjectassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="assignment_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultysubjectassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("role", "INSTRUCTOR")
                ),
                fields=("faculty", "section"),
                name="uniq_active_instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="facultysubjectassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("role", "COURSE_COORDINATOR")
                ),
                fields=("offering",),
                name="one_active_coordinator_per_offering",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                fields=("section", "date", "start_time"), name="uniq_attendance_session"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="attendance_session_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "term"), name="uniq_semester_term"
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="semester_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="orientationseminar",
            constraint=models.UniqueConstraint(
                fields=("semester", "held_on", "title"), name="uniq_ros"
            ),
        ),
        migrations.AddConstraint(
            model_name="examcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exam_end__gte", models.F("exam_start")),
                    ("exam_start__gte", models.F("registration_closes")),
                    ("registration_closes__gte", models.F("registration_opens")),
                ),
                name="exam_cycle_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="electiveproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("credits__gt", 0)), name="elective_proposal_credits"
            ),
        ),
        migrations.AddConstraint(
            model_name="electiveproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("course__isnull", False),
                    models.Q(("proposed_title", ""), _negated=True),
                    _connector="OR",
                ),
                name="elective_proposal_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseoffering",
            constraint=models.UniqueConstraint(
                fields=("course", "semester"), name="uniq_offering_course_semester"
            ),
        ),
        migrations.AddConstraint(
            model_name="thirdattemptcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "SUBMITTED",
                            "DEAN_RECOMMENDED",
                            "DEAN_NOT_RECOMMENDED",
                            "VC_APPROVED",
                        ],
                    )
                ),
                fields=("enrollment",),
                name="one_open_third_attempt_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="thirdattemptcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vc_at__isnull", True), ("dean_at__isnull", False), _connector="OR"
                ),
                name="third_attempt_vc_after_dean",
            ),
        ),
        migrations.AddConstraint(
            model_name="examregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "REGISTERED")),
                fields=("exam", "enrollment"),
                name="uniq_active_exam_registration",
            ),
        ),
        migrations.AddConstraint(
            model_name="examregistration",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_no__gte", 1), ("attempt_no__lte", 3)),
                name="registration_attempt_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="examregistration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempt_no__lt", 3),
                    ("third_attempt_case__isnull", False),
                    _connector="OR",
                ),
                name="third_attempt_needs_case",
            ),
        ),
    ]
