"""Seed version 1 of the academic regulatory parameters (frozen copy of
coursework/academic/parameters.py at the time of Step 5A)."""
import datetime

from django.db import migrations

PARAMETERS = [['coursework.structure.mandatory_taught_courses',
  3,
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A)',
  ''],
 ['coursework.structure.mandatory_activities',
  3,
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A)',
  ''],
 ['coursework.category_of_entry_qualification',
  {'BTECH': 'I', 'MTECH': 'II', 'PG': 'III'},
  'CONFIGURABLE',
  'React journeyData.ts (Regulations July 2026 transcription)',
  'RD-43'],
 ['coursework.required_credits',
  {'I': 23, 'II': 17, 'III': 20},
  'CONFIGURABLE',
  'React journeyData.ts (Regulations July 2026 transcription)',
  'RD-C1'],
 ['coursework.electives_required',
  {'I': 3, 'II': 1, 'III': 2},
  'AMBIGUOUS',
  'React journeyData.ts (Regulations July 2026 transcription)',
  'RD-08'],
 ['coursework.min_gpa', '6.00', 'CONFIRMED', 'Academic source supplied by DYPIU (Step 5A)', 'RD-C3'],
 ['coursework.course_pass_min_marks',
  '40',
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): minimum 40 marks (D)',
  'RD-01'],
 ['coursework.course_pass_min_applies_to',
  'COURSE',
  'AMBIGUOUS',
  "Academic source supplied by DYPIU (Step 5A): 'each course component' may mean each course or each "
  'assessment component',
  'RD-01'],
 ['coursework.continuation_min_grade',
  'C+',
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A)',
  'RD-02'],
 ['coursework.ethics_module_required',
  True,
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): Research Methodology & Ethics has a mandatory '
  'ethics/plagiarism module',
  ''],
 ['grading.scheme',
  {'mode': 'ABSOLUTE',
   'rounding': 'HALF_UP_TO_INTEGER',
   'bands': [['A+', 91, '10'],
             ['A', 81, '9'],
             ['B+', 71, '8'],
             ['B', 61, '7'],
             ['C+', 51, '6'],
             ['C', 41, '5'],
             ['D', 40, '4']],
   'fail': ['F', '0'],
   'order': ['F', 'D', 'C', 'C+', 'B', 'B+', 'A', 'A+']},
  'AMBIGUOUS',
  'Requirements brief (Django docs/REQUIREMENTS.md) (Implementation Guidelines bands); React states relative '
  'grading',
  'RD-01, RD-02, RD-40'],
 ['assessment.default_weights',
  {'CONTINUOUS': 50, 'END_TERM': 50},
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): 50% Continuous Assessment, 50% End-term',
  ''],
 ['assessment.elective_reweighting_limit_percent',
  10,
  'CONFIGURABLE',
  'Requirements brief (Django docs/REQUIREMENTS.md): adaptable ±10% weighting template for electives',
  'RD-37'],
 ['assessment.elective_reweighting_approver', None, 'UNRESOLVED', 'Not stated', 'RD-37, RD-38'],
 ['attendance.physical_only',
  True,
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): physical attendance requirement',
  ''],
 ['attendance.min_percent',
  {'FT': 75, 'PT': None},
  'AMBIGUOUS',
  "React journeyData.ts (Regulations July 2026 transcription): full-time 'min 75% attendance'; basis (per "
  'course/overall) and part-time rule not stated',
  'RD-26'],
 ['exam.cycles',
  ['JAN_JUN', 'JUL_DEC'],
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): January–June and July–December cycles',
  'RD-35'],
 ['exam.max_regular_attempts', 2, 'CONFIRMED', 'Academic source supplied by DYPIU (Step 5A)', 'RD-C3'],
 ['exam.max_attempts_with_approval',
  3,
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): third (final) attempt case',
  'RD-16'],
 ['exam.attempt_window_years',
  2,
  'CONFIRMED',
  'React journeyData.ts (Regulations July 2026 transcription): within 2 years of enrolment',
  'RD-C3'],
 ['exam.attempt_window_start',
  'ENROLMENT',
  'AMBIGUOUS',
  "React M12 'of enrolment' vs Django legacy 'first attempt'",
  'RD-C3'],
 ['exam.absent_counts_as_attempt', None, 'UNRESOLVED', 'Not stated', ''],
 ['exam.reattempt_carries_continuous_assessment', None, 'UNRESOLVED', 'Not stated', ''],
 ['exam.requires_fee_clearance',
  True,
  'CONFIGURABLE',
  'React journeyData.ts (Regulations July 2026 transcription) M10: no admission to the exam unless tuition '
  'fees and hostel/library dues are cleared',
  ''],
 ['third_attempt.review_chain',
  ['DEAN_RND', 'VC_OPERATOR'],
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): Dean R&D review followed by VC approval',
  'RD-16'],
 ['third_attempt.mentor_required',
  None,
  'UNRESOLVED',
  'React M12 mentions a weekly-tracking mentor; not stated in the Step 5A source',
  'RD-16'],
 ['elective.approval_authority',
  None,
  'UNRESOLVED',
  "React M9.1 names 'DC / Dean of Research'; approving capability not confirmed",
  'RD-38'],
 ['elective.supervisor_recommendation_required',
  None,
  'UNRESOLVED',
  "Academic source supplied by DYPIU (Step 5A): 'where required'",
  'RD-38'],
 ['activity.required_artefacts',
  {'INDUSTRIAL_TRAINING': ['PLAN', 'LOGBOOK', 'REPORT', 'POSTER'],
   'CONFERENCE_WORKSHOP': ['REFLECTIVE_NOTE'],
   'RESEARCH_SEMINAR': ['PRESENTATION']},
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A)',
  'RD-37'],
 ['activity.artefacts_in_order',
  {'INDUSTRIAL_TRAINING': True},
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): plan → logbook → report → poster flow',
  ''],
 ['result.custody_chain',
  ['PREPARE', 'VERIFY:RND_CELL_OPERATOR', 'RATIFY:COE_OPERATOR'],
  'CONFIRMED',
  'Academic source supplied by DYPIU (Step 5A): Course Coordinator / SDRC → R&D Cell → COE',
  '']]


def seed(apps, schema_editor):
    Param = apps.get_model("coursework", "AcademicRuleParameter")
    for key, value, status, source, reference in PARAMETERS:
        if not Param.objects.filter(key=key).exists():
            Param.objects.create(key=key, version=1, value=value, status=status, source=source,
                                 reference=reference, effective_from=datetime.date(2026, 7, 1),
                                 change_reason="Initial seed (Step 5A)")


class Migration(migrations.Migration):
    dependencies = [("coursework", "0002_academicruleparameter_academicyear_and_more")]
    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
