# Generated by Django 5.2.17 on 2026-09-25 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_retire_coursework_third_attempt_chain"),
        ("coursework", "0003_seed_rule_parameters"),
        ("identity", "0003_stable_derived_constraint"),
        ("scholars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectiveList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for approval"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned for revision"),
                        ],
                        default="DRAFT",
                        max_length=9,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=0)),
                (
                    "approval_chain",
                    models.JSONField(
                        default=list, help_text="Capabilities snapshot at submission"
                    ),
                ),
                (
                    "prepared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ElectiveListDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.PositiveSmallIntegerField()),
                ("capability", models.CharField(max_length=30)),
                ("approved", models.BooleanField()),
                ("remarks", models.TextField(blank=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ElectiveListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intake_capacity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cleared", models.BooleanField()),
                (
                    "reference",
                    models.CharField(
                        help_text="Receipt / accounts reference", max_length=120
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HallTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="System identifier; official format unresolved",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("verification_code", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "Issued"), ("REVOKED", "Revoked")],
                        default="ISSUED",
                        max_length=7,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ParameterChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed by the supplied source"),
                            (
                                "CONFIGURABLE",
                                "Configurable (value known, pending institutional confirmation)",
                            ),
                            (
                                "AMBIGUOUS",
                                "Ambiguous (sources conflict or wording unclear)",
                            ),
                            (
                                "UNRESOLVED",
                                "Unresolved (no value; requires institutional decision)",
                            ),
                        ],
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("effective_from", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending approval"),
                            ("APPROVED", "Approved (version created)"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                (
                    "proposed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_remarks", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-proposed_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionPaperSetterAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPOINTED", "Appointed"),
                            ("PAPER_RECEIVED", "Paper received"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPOINTED",
                        max_length=14,
                    ),
                ),
                ("basis", models.CharField(max_length=255)),
                ("appointed_as", models.CharField(max_length=30)),
                (
                    "appointed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RevaluationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("REVIEWED_UNCHANGED", "Reviewed: no change"),
                            (
                                "REVISED_PENDING",
                                "Revised result awaiting verification / ratification",
                            ),
                            ("COMPLETED", "Revised result ratified"),
                            ("REJECTED", "Revised result not ratified"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_as", models.CharField(blank=True, max_length=30)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RevaluationMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_marks",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("revised_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SemesterRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REGISTERED",
                        max_length=10,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranscriptIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("verification_code", models.CharField(max_length=32, unique=True)),
                ("provisional", models.BooleanField()),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="academicruleparameter",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Approver; null only for the initial seed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="is_current",
            field=models.BooleanField(
                default=True, help_text="The result in force for the attempt"
            ),
        ),
        migrations.AddField(
            model_name="courseresult",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                help_text="Original result (revaluation)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="coursework.courseresult",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="registration_closes",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="semester",
            name="registration_opens",
            field=models.DateField(
                blank=True, help_text="Semester registration window", null=True
            ),
        ),
        migrations.AlterField(
            model_name="academicruleparameter",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Proposer; null only for the initial seed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AlterField(
            model_name="courseresult",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="coursework.courseattempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ratified_at__isnull", False),
                        ("status", "RATIFIED"),
                        ("verified_at__isnull", False),
                    ),
                    models.Q(
                        ("ratified_at__isnull", True),
                        ("status", "VERIFIED"),
                        ("verified_at__isnull", False),
                    ),
                    models.Q(
                        ("ratified_at__isnull", True),
                        ("status__in", ["PREPARED", "RETURNED"]),
                    ),
                    _connector="OR",
                ),
                name="result_status_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("attempt",),
                name="one_current_result_per_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="semester",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("registration_closes__isnull", True),
                        ("registration_opens__isnull", True),
                    ),
                    models.Q(
                        ("registration_closes__gte", models.F("registration_opens")),
                        ("registration_opens__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="semester_registration_window",
            ),
        ),
        migrations.AddField(
            model_name="electivelist",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="electivelist",
            name="prepared_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electivelist",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.school",
            ),
        ),
        migrations.AddField(
            model_name="electivelist",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="elective_lists",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="electivelistdecision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="electivelistdecision",
            name="elective_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="coursework.electivelist",
            ),
        ),
        migrations.AddField(
            model_name="electivelistitem",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.course",
            ),
        ),
        migrations.AddField(
            model_name="electivelistitem",
            name="elective_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="coursework.electivelist",
            ),
        ),
        migrations.AddField(
            model_name="feeclearance",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="feeclearance",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_clearances",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="feeclearance",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_clearances",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="hallticket",
            name="issued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="hallticket",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hall_tickets",
                to="coursework.examregistration",
            ),
        ),
        migrations.AddField(
            model_name="hallticket",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="parameterchangerequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="parameterchangerequest",
            name="proposed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="academicruleparameter",
            name="change_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resulting_version",
                to="coursework.parameterchangerequest",
            ),
        ),
        migrations.AddField(
            model_name="questionpapersetterappointment",
            name="appointed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="questionpapersetterappointment",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="setter_appointments",
                to="coursework.exam",
            ),
        ),
        migrations.AddField(
            model_name="questionpapersetterappointment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="questionpapersetterappointment",
            name="setter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="revaluationcase",
            name="original_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revaluation_cases",
                to="coursework.courseresult",
            ),
        ),
        migrations.AddField(
            model_name="revaluationcase",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="revaluationcase",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="revaluationcase",
            name="revised_result",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revaluation_origin",
                to="coursework.courseresult",
            ),
        ),
        migrations.AddField(
            model_name="revaluationmark",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.assessment",
            ),
        ),
        migrations.AddField(
            model_name="revaluationmark",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="marks",
                to="coursework.revaluationcase",
            ),
        ),
        migrations.AddField(
            model_name="semesterregistration",
            name="fee_clearance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="coursework.feeclearance",
            ),
        ),
        migrations.AddField(
            model_name="semesterregistration",
            name="registered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="semesterregistration",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="semester_registrations",
                to="scholars.scholar",
            ),
        ),
        migrations.AddField(
            model_name="semesterregistration",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registrations",
                to="coursework.semester",
            ),
        ),
        migrations.AddField(
            model_name="transcriptissue",
            name="issued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="identity.person",
            ),
        ),
        migrations.AddField(
            model_name="transcriptissue",
            name="scholar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transcript_issues",
                to="scholars.scholar",
            ),
        ),
        migrations.AddConstraint(
            model_name="electivelist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("department__isnull", False), ("school__isnull", True)),
                    models.Q(("department__isnull", True), ("school__isnull", False)),
                    _connector="OR",
                ),
                name="elective_list_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="electivelistitem",
            constraint=models.UniqueConstraint(
                fields=("elective_list", "course"), name="uniq_elective_list_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeclearance",
            constraint=models.UniqueConstraint(
                fields=("scholar", "semester"), name="uniq_fee_clearance"
            ),
        ),
        migrations.AddConstraint(
            model_name="hallticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ISSUED")),
                fields=("registration",),
                name="one_live_hall_ticket",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameterchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "PENDING")),
                fields=("key",),
                name="one_pending_change_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameterchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decided_by__isnull", True), ("state", "PENDING")),
                    models.Q(
                        models.Q(("state", "PENDING"), _negated=True),
                        ("decided_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="change_decision_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionpapersetterappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "WITHDRAWN"), _negated=True),
                fields=("exam", "setter"),
                name="uniq_active_setter_appointment",
            ),
        ),
        migrations.AddConstraint(
            model_name="revaluationcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["REQUESTED", "REVISED_PENDING"])),
                fields=("original_result",),
                name="one_open_revaluation",
            ),
        ),
        migrations.AddConstraint(
            model_name="revaluationmark",
            constraint=models.UniqueConstraint(
                fields=("case", "assessment"), name="uniq_revaluation_mark"
            ),
        ),
        migrations.AddConstraint(
            model_name="revaluationmark",
            constraint=models.CheckConstraint(
                condition=models.Q(("revised_marks__gte", 0)),
                name="revaluation_marks_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="semesterregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "REGISTERED")),
                fields=("scholar", "semester"),
                name="uniq_active_semester_registration",
            ),
        ),
        migrations.AddConstraint(
            model_name="transcriptissue",
            constraint=models.UniqueConstraint(
                fields=("scholar", "version"), name="uniq_transcript_version"
            ),
        ),
    ]
