# Generated by Django 5.2.17 on 2026-09-24 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("scholars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminerNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("affiliation", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("is_foreign", models.BooleanField(default=False)),
                (
                    "selected",
                    models.BooleanField(
                        default=False, help_text="One of the 3 chosen by the VC"
                    ),
                ),
                (
                    "replaced",
                    models.BooleanField(
                        default=False, help_text="Replaced after failing to report"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DCReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("opened_on", models.DateField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONTINUE", "Continue with conditions"),
                            ("CANCEL", "Cancel registration"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decided_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dc_reviews",
                        to="scholars.scholar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DegreeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("certificate_no", models.CharField(blank=True, max_length=50)),
                ("issued_on", models.DateField(blank=True, null=True)),
                (
                    "academic_council_notified_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degree_award",
                        to="scholars.scholar",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExaminerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatched_on", models.DateField()),
                ("reminded_on", models.DateField(blank=True, null=True)),
                ("received_on", models.DateField(blank=True, null=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMMEND", "Commended for award"),
                            ("REVISE", "Revise and resubmit"),
                            ("NOT_COMMEND", "Not commended"),
                        ],
                        max_length=12,
                    ),
                ),
                ("document", models.FileField(blank=True, upload_to="thesis/reports/")),
                (
                    "examiner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="lifecycle.examinernomination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhaseTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_phase", models.PositiveSmallIntegerField()),
                ("to_phase", models.PositiveSmallIntegerField()),
                ("from_status", models.CharField(max_length=10)),
                ("to_status", models.CharField(max_length=10)),
                ("note", models.TextField(blank=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="Synopsis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_on", models.DateField()),
                ("document", models.FileField(blank=True, upload_to="synopsis/")),
                ("open_seminar_date", models.DateField(blank=True, null=True)),
                ("tac_cleared_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synopses",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "synopses",
                "ordering": ["scholar", "submitted_on"],
            },
        ),
        migrations.CreateModel(
            name="Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("submitted_on", models.DateField()),
                ("document", models.FileField(blank=True, upload_to="thesis/")),
                (
                    "plagiarism_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "plagiarism_report",
                    models.FileField(blank=True, upload_to="thesis/plagiarism/"),
                ),
                ("fees_paid", models.BooleanField(default=False)),
                (
                    "panel_approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theses",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "theses",
                "ordering": ["scholar", "submitted_on"],
            },
        ),
        migrations.AddField(
            model_name="examinernomination",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominations",
                to="lifecycle.thesis",
            ),
        ),
        migrations.CreateModel(
            name="Viva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_on", models.DateField()),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("candidate_notified_on", models.DateField(blank=True, null=True)),
                ("invitation_published_on", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("NOT_SATISFACTORY", "Not satisfactory"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("report", models.FileField(blank=True, upload_to="viva/")),
                (
                    "dpep",
                    models.ForeignKey(
                        limit_choices_to={"type": "DPEP"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.committee",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vivas",
                        to="lifecycle.thesis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "vivas",
            },
        ),
        migrations.CreateModel(
            name="ProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_no",
                    models.PositiveSmallIntegerField(
                        help_text="1 = first six months after registration"
                    ),
                ),
                ("due_date", models.DateField()),
                ("submitted_on", models.DateField(blank=True, null=True)),
                ("document", models.FileField(blank=True, upload_to="progress/")),
                ("tac_meeting_date", models.DateField(blank=True, null=True)),
                ("tac_minutes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting TAC review"),
                            ("SATISFACTORY", "Satisfactory"),
                            ("UNSATISFACTORY", "Unsatisfactory (warning)"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "dc_review",
                    models.ForeignKey(
                        blank=True,
                        help_text="The DC review that dealt with this warning",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warnings",
                        to="lifecycle.dcreview",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["scholar", "period_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scholar", "period_no"), name="uniq_progress_period"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResearchProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("title", models.CharField(max_length=500)),
                ("document", models.FileField(blank=True, upload_to="proposals/")),
                ("submitted_on", models.DateField()),
                ("seminar_date", models.DateField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending evaluation"),
                            ("RECOMMENDED", "Recommended"),
                            ("MINOR_REVISION", "Recommended with minor modifications"),
                            ("RESUBMIT", "Resubmit after major revision"),
                            ("NOT_RECOMMENDED", "Not recommended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.committee",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="scholars.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["scholar", "attempt_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scholar", "attempt_no"), name="uniq_proposal_attempt"
                    )
                ],
            },
        ),
    ]
